# Generated by Django 5.2.13 on 2026-04-19 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_freelancerprofile_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminderemail',
            name='email_message_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='reminderemail',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='reminderemail',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('failed', 'Failed'), ('paused', 'Paused')], default='draft', max_length=20),
        ),
    ]
